# Generated by Django 4.0.4 on 2022-07-10 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=180)),
                ('question', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
