# Generated by Django 4.0.4 on 2022-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
