# Generated by Django 4.0.4 on 2022-07-10 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_questions_id_remove_questions_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
